development:
  adapter: postgresql
  database: epb_addressing
  username: postgres
test:
  adapter: postgresql
  database: epb_addressing_test
  username: postgres
  password: <%= ENV['DOCKER_POSTGRES_PASSWORD'] %>
production:
  adapter: postgresql
  database: epb
  pool: 62
  url: <%= ENV['DATABASE_URL'] %>